name: Coding Standards

on:
  pull_request:
    branches:
      - master

permissions:
  checks: write
  contents: read

jobs:
  check:
    name: Set up and run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: 'package.json'

      - name: Install Node.js dependencies
        run: npm i

      - name: Run linters
        uses: wearerequired/lint-action@v3
        with:
          continue_on_error: false
          eslint: true
